--[[

[CHANGELOGS]

--# 2026
>>

MAY 23: Revamp.
MAY 23: Enabled cript Sync to VSC + All libs.

MAY 17: Removed expectValue(), expectInArray(), & expectInDict() from params x.x
MAY 17: Added method expectValue() to params + minor improvements.
MAY 17: Added methods expectInArray() & expectInDict() to params.
MAY 17: constructor() and ready() are now called as methods, not functions.
MAY 17: Swapped RenderStepped to Heartbeat in kernel - Server cannot access.

]]