--[[

[CHANGELOGS]

--# 2026
>>

MAY 27: Updated the inputChangeLogger daemon.
MAY 27: Removed getPreferredInputStyled module.
MAY 27: Updated most utils.

MAY 26: Updated try to validate the error handler on the initial call.
MAY 26: Removed redundant try statement checks in boot.

MAY 24: Updated README file; Will add a custom one to GitHub instead of using it.
MAY 24: Updated boot failure logs to be more legible + use new formatting.
MAY 24: Added function "deverr" to console.
MAY 24: Updated serviceTemplate, interfaceService, and added a comment in boot.

MAY 23: Revamp.
MAY 23: Enabled cript Sync to VSC + All libs.

MAY 17: Removed expectValue(), expectInArray(), & expectInDict() from params x.x
MAY 17: Added method expectValue() to params + minor improvements.
MAY 17: Added methods expectInArray() & expectInDict() to params.
MAY 17: constructor() and ready() are now called as methods, not functions.
MAY 17: Swapped RenderStepped to Heartbeat in kernel - Server cannot access.

]]