--[=[
	[INFO]
	author: @halosviel
	created: 2026 May 22
	
	[DESCRIPTION]
	
	[NOTES]
	- 
]=]

-- [REQUIRES]

-- [VARIABLES]

-- [TYPES]
type self = {
	-- [CONFIG]

	-- [ENTRIES]

	-- [FUNCTIONS]
	constructor: ( self: self ) -> nil,
	ready: ( self: self ) -> nil
}
export type Service = self

-->

return {
	constructor = function(self: self)
		
	end,
	
	ready = function(self: self)
		
	end,
} :: self